import Foundation

enum CoachAPIError: Error, LocalizedError {
    case notConfigured
    case http(status: Int, message: String)

    var errorDescription: String? {
        switch self {
        case .notConfigured:
            return "Exercise API URL is not configured. Add ExerciseAPIBaseURL in Info.plist."
        case .http(_, let message):
            return message
        }
    }
}

struct CoachPublicConfig: Equatable {
    var trainerName: String
    var coachSubtitle: String
    var welcomeTagline: String
    var welcomeDisclaimer: String
    var learnMoreURL: URL?
    var quickChips: [String]

    static func `default`() -> CoachPublicConfig {
        CoachPublicConfig(
            trainerName: "Aura",
            coachSubtitle: "Personal Trainer | AI powered",
            welcomeTagline: "Your very own Personal Trainer | AI by Trakkit",
            welcomeDisclaimer: "Messages are generated by AI. Some may be inaccurate or inappropriate.",
            learnMoreURL: URL(string: "https://trakkit.app"),
            quickChips: ["Full Body Workout", "Quick Stretch", "Cardio Session"]
        )
    }
}

struct CoachChatTurn: Codable {
    var role: String
    var content: String
}

struct AIGeneratedWorkoutPlan: Equatable {
    var title: String
    var description: String
    var exerciseIds: [String]
    var coachMessage: String
}

struct CoachAPIService {
    static let shared = CoachAPIService()

    private init() {}

    func fetchPublicConfig() async throws -> CoachPublicConfig {
        guard let base = ExerciseAPIConfiguration.baseURL else {
            throw CoachAPIError.notConfigured
        }
        guard let url = ExerciseAPIHTTPClient.apiURL(path: "api/v1/ai/coach/config", base: base) else {
            throw CoachAPIError.http(status: 0, message: "Invalid coach config URL")
        }
        var request = ExerciseAPIHTTPClient.preparedRequest(
            url: url,
            cachePolicy: .reloadIgnoringLocalCacheData
        )
        request.setValue("application/json", forHTTPHeaderField: "Accept")
        addAppKey(to: &request)
        let (data, response) = try await performRequest(request, context: "fetching coach config", longRunning: false)
        try validate(response: response, data: data)
        do {
            return try decodeConfig(data)
        } catch {
            let snippet = Self.bodySnippet(data: data)
            throw CoachAPIError.http(
                status: 200,
                message: "Could not parse coach config. Body starts with: \(snippet)"
            )
        }
    }

    func sendChat(userName: String?, messages: [CoachChatTurn]) async throws -> String {
        guard let base = ExerciseAPIConfiguration.chatBaseURL else {
            throw CoachAPIError.notConfigured
        }
        guard let url = ExerciseAPIHTTPClient.apiURL(path: "api/v1/ai/coach/chat", base: base) else {
            throw CoachAPIError.http(status: 0, message: "Invalid coach chat URL")
        }
        var request = ExerciseAPIHTTPClient.preparedRequest(
            url: url,
            cachePolicy: .reloadIgnoringLocalCacheData,
            timeout: 120
        )
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue("application/json", forHTTPHeaderField: "Accept")
        addAppKey(to: &request)
        let body = CoachChatRequestBody(userName: userName, messages: messages)
        request.httpBody = try JSONEncoder().encode(body)

        let (data, response) = try await performRequest(request, context: "chatting", longRunning: true)
        try validate(response: response, data: data)
        let decoder = JSONDecoder()
        let reply: CoachChatReply
        do {
            reply = try decoder.decode(CoachChatReply.self, from: data)
        } catch {
            let snippet = Self.bodySnippet(data: data)
            throw CoachAPIError.http(
                status: 200,
                message: "Could not parse coach reply. Body starts with: \(snippet)"
            )
        }
        let text = reply.reply.trimmingCharacters(in: .whitespacesAndNewlines)
        if text.isEmpty { throw CoachAPIError.http(status: 200, message: "Empty reply from coach.") }
        return text
    }

    func generateWorkout(bodyPart: MuscleGroup, userName: String?) async throws -> AIGeneratedWorkoutPlan {
        guard let base = ExerciseAPIConfiguration.chatBaseURL else {
            throw CoachAPIError.notConfigured
        }
        guard let url = ExerciseAPIHTTPClient.apiURL(path: "api/v1/ai/coach/generate-workout", base: base) else {
            throw CoachAPIError.http(status: 0, message: "Invalid generate-workout URL")
        }
        var request = ExerciseAPIHTTPClient.preparedRequest(
            url: url,
            cachePolicy: .reloadIgnoringLocalCacheData,
            timeout: 120
        )
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue("application/json", forHTTPHeaderField: "Accept")
        addAppKey(to: &request)
        let body = GenerateWorkoutRequestBody(
            bodyPart: bodyPart.rawValue,
            userName: userName
        )
        request.httpBody = try JSONEncoder().encode(body)

        let (data, response) = try await performRequest(request, context: "generating workout plan", longRunning: true)
        try validate(response: response, data: data)
        let dto: GenerateWorkoutResponse
        do {
            dto = try JSONDecoder().decode(GenerateWorkoutResponse.self, from: data)
        } catch {
            let snippet = Self.bodySnippet(data: data)
            throw CoachAPIError.http(
                status: 200,
                message: "Could not parse workout plan. Body starts with: \(snippet)"
            )
        }
        let ids = dto.exerciseIds.map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }.filter { !$0.isEmpty }
        guard ids.count == 5 else {
            throw CoachAPIError.http(status: 200, message: "Plan must include exactly 5 exercises.")
        }
        let title = dto.title.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !title.isEmpty else {
            throw CoachAPIError.http(status: 200, message: "Plan title was empty.")
        }
        return AIGeneratedWorkoutPlan(
            title: title,
            description: dto.description.trimmingCharacters(in: .whitespacesAndNewlines),
            exerciseIds: ids,
            coachMessage: dto.coachMessage.trimmingCharacters(in: .whitespacesAndNewlines)
        )
    }

    private func addAppKey(to request: inout URLRequest) {
        if let key = ExerciseAPIConfiguration.publicAPIKey {
            request.setValue(key, forHTTPHeaderField: "X-App-Key")
        }
    }

    private func performRequest(
        _ request: URLRequest,
        context: String,
        longRunning: Bool
    ) async throws -> (Data, URLResponse) {
        do {
            if longRunning {
                return try await ExerciseAPIHTTPClient.longRunningData(for: request)
            }
            return try await ExerciseAPIHTTPClient.data(for: request)
        } catch {
            let code = (error as? URLError)?.code
            let codeText = code.map { String($0.rawValue) } ?? "n/a"
            let desc = (error as? URLError)?.localizedDescription ?? error.localizedDescription
            let urlText = request.url?.absoluteString ?? "(unknown URL)"
            throw CoachAPIError.http(
                status: 0,
                message: "Network error while \(context): \(desc) (code: \(codeText)) for \(urlText)"
            )
        }
    }

    private func validate(response: URLResponse, data: Data) throws {
        guard let http = response as? HTTPURLResponse else { return }
        guard (200...299).contains(http.statusCode) else {
            let msg = Self.parseErrorMessage(data: data, fallbackStatus: http.statusCode)
            throw CoachAPIError.http(status: http.statusCode, message: msg)
        }
    }

    private static func parseErrorMessage(data: Data, fallbackStatus: Int) -> String {
        if let obj = try? JSONDecoder().decode(CoachErrorBody.self, from: data),
           let e = obj.error?.trimmingCharacters(in: .whitespacesAndNewlines), !e.isEmpty {
            return e
        }
        if let s = String(data: data, encoding: .utf8)?.trimmingCharacters(in: .whitespacesAndNewlines), !s.isEmpty {
            if let pre = extractPreText(from: s) { return pre }
            if s.contains("<html") || s.contains("<!DOCTYPE") {
                return "Coach request failed (\(fallbackStatus)). Check API URL configuration."
            }
            return s.count > 240 ? String(s.prefix(240)) + "…" : s
        }
        return "Request failed (\(fallbackStatus))."
    }

    private static func extractPreText(from html: String) -> String? {
        guard let open = html.range(of: "<pre>", options: .caseInsensitive),
              let close = html.range(of: "</pre>", options: .caseInsensitive, range: open.upperBound..<html.endIndex)
        else { return nil }
        let text = String(html[open.upperBound..<close.lowerBound])
            .trimmingCharacters(in: .whitespacesAndNewlines)
        return text.isEmpty ? nil : text
    }

    private static func bodySnippet(data: Data) -> String {
        let s = String(data: data, encoding: .utf8)?
            .trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        if s.isEmpty { return "(empty body)" }
        let oneLine = s.replacingOccurrences(of: "\\s+", with: " ", options: .regularExpression)
        if oneLine.count > 220 { return String(oneLine.prefix(220)) + "…" }
        return oneLine
    }

    private func decodeConfig(_ data: Data) throws -> CoachPublicConfig {
        let dto = try JSONDecoder().decode(CoachPublicConfigDTO.self, from: data)
        var base = CoachPublicConfig.default()
        if let t = dto.trainerName?.trimmingCharacters(in: .whitespacesAndNewlines), !t.isEmpty {
            base.trainerName = t
        }
        if let t = dto.coachSubtitle?.trimmingCharacters(in: .whitespacesAndNewlines), !t.isEmpty {
            base.coachSubtitle = t
        }
        if let t = dto.welcomeTagline?.trimmingCharacters(in: .whitespacesAndNewlines), !t.isEmpty {
            base.welcomeTagline = t
        }
        if let t = dto.welcomeDisclaimer?.trimmingCharacters(in: .whitespacesAndNewlines), !t.isEmpty {
            base.welcomeDisclaimer = t
        }
        if let raw = dto.learnMoreUrl?.trimmingCharacters(in: .whitespacesAndNewlines),
           raw.hasPrefix("http"), let u = URL(string: raw) {
            base.learnMoreURL = u
        }
        if let chips = dto.quickChips {
            let cleaned = chips.map { String($0).trimmingCharacters(in: .whitespacesAndNewlines) }.filter { !$0.isEmpty }
            if !cleaned.isEmpty { base.quickChips = cleaned }
        }
        return base
    }
}

private struct CoachPublicConfigDTO: Decodable {
    let trainerName: String?
    let coachSubtitle: String?
    let welcomeTagline: String?
    let welcomeDisclaimer: String?
    let learnMoreUrl: String?
    let quickChips: [String]?
}

private struct CoachChatRequestBody: Encodable {
    let userName: String?
    let messages: [CoachChatTurn]
}

private struct CoachChatReply: Decodable {
    let reply: String
}

private struct CoachErrorBody: Decodable {
    let error: String?
}

private struct GenerateWorkoutRequestBody: Encodable {
    let bodyPart: String
    let userName: String?
}

private struct GenerateWorkoutResponse: Decodable {
    let title: String
    let description: String
    let exerciseIds: [String]
    let coachMessage: String
}
