import Foundation

struct SampleData {
    static let workouts: [Workout] = [
        Workout(
            id: "workout_1",
            title: "Full Body HIIT",
            description: "High-intensity interval training that targets your entire body. Perfect for burning calories and building endurance.",
            category: .hiit,
            difficulty: .intermediate,
            duration: 30,
            videoURL: "https://www.youtube.com/watch?v=ml6cT4AZdqI",
            videoSourceType: .youtube,
            videoId: "ml6cT4AZdqI",
            thumbnailURL: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800",
            isPremium: true,
            exercises: [],
            caloriesBurned: 350
        ),
        Workout(
            id: "workout_2",
            title: "Beginner Yoga Flow",
            description: "A gentle introduction to yoga with basic poses and breathing exercises. Perfect for beginners.",
            category: .yoga,
            difficulty: .beginner,
            duration: 20,
            videoURL: "https://vimeo.com/148751763",
            videoSourceType: .vimeo,
            videoId: "148751763",
            thumbnailURL: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800",
            isPremium: false,
            exercises: [],
            caloriesBurned: 120
        ),
        Workout(
            id: "workout_3",
            title: "Upper Body Strength",
            description: "Build muscle and strength in your chest, shoulders, back, and arms with this comprehensive upper body workout.",
            category: .strength,
            difficulty: .advanced,
            duration: 45,
            videoURL: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
            videoSourceType: .directURL,
            thumbnailURL: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800",
            isPremium: true,
            exercises: [],
            caloriesBurned: 450
        ),
        Workout(
            id: "workout_4",
            title: "Cardio Blast",
            description: "Get your heart pumping with this high-energy cardio session. Great for improving cardiovascular health.",
            category: .cardio,
            difficulty: .intermediate,
            duration: 25,
            videoURL: "https://youtu.be/dQw4w9WgXcQ",
            videoSourceType: .youtube,
            videoId: "dQw4w9WgXcQ",
            thumbnailURL: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800",
            isPremium: false,
            exercises: [],
            caloriesBurned: 280
        ),
        Workout(
            id: "workout_5",
            title: "Core Crusher",
            description: "Target your abs and core muscles with this intense core-focused workout. Suitable for all fitness levels.",
            category: .strength,
            difficulty: .allLevels,
            duration: 15,
            videoURL: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
            videoSourceType: .directURL,
            thumbnailURL: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800",
            isPremium: false,
            exercises: [],
            caloriesBurned: 150
        ),
        Workout(
            id: "workout_6",
            title: "Power Yoga",
            description: "A dynamic and challenging yoga practice that builds strength, flexibility, and mental focus.",
            category: .yoga,
            difficulty: .intermediate,
            duration: 40,
            videoURL: "https://player.vimeo.com/video/148751763",
            videoSourceType: .vimeo,
            videoId: "148751763",
            thumbnailURL: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800",
            isPremium: true,
            exercises: [],
            caloriesBurned: 200
        ),
        Workout(
            id: "workout_7",
            title: "Leg Day",
            description: "The ultimate lower body workout targeting quads, hamstrings, glutes, and calves. Not for the faint of heart!",
            category: .strength,
            difficulty: .advanced,
            duration: 50,
            videoURL: "https://www.youtube.com/embed/jNQXAC9IVRw",
            videoSourceType: .youtube,
            videoId: "jNQXAC9IVRw",
            thumbnailURL: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800",
            isPremium: true,
            exercises: [],
            caloriesBurned: 500
        ),
        Workout(
            id: "workout_8",
            title: "Morning Stretch",
            description: "Start your day right with this gentle stretching routine. Perfect for improving flexibility and reducing stiffness.",
            category: .flexibility,
            difficulty: .beginner,
            duration: 10,
            videoURL: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
            videoSourceType: .directURL,
            thumbnailURL: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800",
            isPremium: false,
            exercises: [],
            caloriesBurned: 50
        ),
        Workout(
            id: "workout_9",
            title: "HIIT Cardio",
            description: "Short bursts of intense exercise followed by brief recovery periods. Maximum calorie burn in minimum time.",
            category: .hiit,
            difficulty: .intermediate,
            duration: 20,
            videoURL: "https://vimeo.com/148751763",
            videoSourceType: .vimeo,
            videoId: "148751763",
            thumbnailURL: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800",
            isPremium: true,
            exercises: [],
            caloriesBurned: 300
        ),
        Workout(
            id: "workout_10",
            title: "Chest & Arms",
            description: "Focus on building a strong chest and defined arms with this targeted strength training session.",
            category: .strength,
            difficulty: .intermediate,
            duration: 35,
            videoURL: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
            videoSourceType: .directURL,
            thumbnailURL: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800",
            isPremium: true,
            exercises: [],
            caloriesBurned: 380
        )
    ]
}

