import { config } from './config.js';
import { firestore, fv } from './firebase.js';
import { docToExercise } from './serialize.js';

const OPENROUTER_URL = 'https://openrouter.ai/api/v1/chat/completions';
const CHAT_TIMEOUT_MS = 60_000;
const VALID_AI_PROVIDERS = new Set(['cloudflare', 'openrouter']);

export const DEFAULT_AI_COACH = Object.freeze({
  systemPrompt: [
    'You are Aura, a friendly and knowledgeable AI personal trainer for the Trakkit fitness app.',
    'Give concise, actionable advice. Prefer short paragraphs and bullets when listing exercises or plans.',
    'If the user asks for medical diagnoses or anything unsafe, decline and suggest consulting a professional.',
  ].join(' '),
  coachSubtitle: 'Personal Trainer | AI powered',
  welcomeTagline: 'Your very own Personal Trainer | AI by Trakkit',
  welcomeDisclaimer:
    'Messages are generated by AI. Some may be inaccurate or inappropriate.',
  learnMoreUrl: 'https://trakkit.app',
  quickChips: ['Full Body Workout', 'Quick Stretch', 'Cardio Session'],
  aiProvider: 'cloudflare',
});

function coachRef() {
  return firestore().collection(config.aiCoachFirestoreCollection).doc(config.aiCoachFirestoreDocId);
}

function normalizeAiProvider(raw) {
  const v = typeof raw === 'string' ? raw.trim().toLowerCase() : '';
  if (VALID_AI_PROVIDERS.has(v)) return v;
  const fallback = config.aiProviderDefault;
  return VALID_AI_PROVIDERS.has(fallback) ? fallback : 'cloudflare';
}

export function isCloudflareConfigured() {
  return Boolean(config.cloudflareAccountId && config.cloudflareAiApiToken);
}

/** @returns {Promise<Record<string, unknown>>} merged settings for admin + server */
export async function readAiCoachSettingsFromFirestore() {
  const snap = await coachRef().get();
  if (!snap.exists) return { ...DEFAULT_AI_COACH };
  const d = snap.data() || {};
  return mergeWithDefaults(d);
}

function mergeWithDefaults(d) {
  const chips = normalizeChips(d.quickChips);
  return {
    systemPrompt: typeof d.systemPrompt === 'string' && d.systemPrompt.trim()
      ? d.systemPrompt.trim()
      : DEFAULT_AI_COACH.systemPrompt,
    coachSubtitle:
      typeof d.coachSubtitle === 'string' && d.coachSubtitle.trim()
        ? d.coachSubtitle.trim()
        : DEFAULT_AI_COACH.coachSubtitle,
    welcomeTagline:
      typeof d.welcomeTagline === 'string' && d.welcomeTagline.trim()
        ? d.welcomeTagline.trim()
        : DEFAULT_AI_COACH.welcomeTagline,
    welcomeDisclaimer:
      typeof d.welcomeDisclaimer === 'string' && d.welcomeDisclaimer.trim()
        ? d.welcomeDisclaimer.trim()
        : DEFAULT_AI_COACH.welcomeDisclaimer,
    learnMoreUrl:
      typeof d.learnMoreUrl === 'string' && d.learnMoreUrl.trim().startsWith('http')
        ? d.learnMoreUrl.trim()
        : DEFAULT_AI_COACH.learnMoreUrl,
    quickChips: chips.length ? chips : [...DEFAULT_AI_COACH.quickChips],
    aiProvider: normalizeAiProvider(d.aiProvider),
    cloudflareModel:
      typeof d.cloudflareModel === 'string' && d.cloudflareModel.trim()
        ? d.cloudflareModel.trim()
        : null,
    openRouterModel:
      typeof d.openRouterModel === 'string' && d.openRouterModel.trim()
        ? d.openRouterModel.trim()
        : null,
  };
}

function normalizeChips(raw) {
  if (!raw) return [];
  if (Array.isArray(raw)) {
    return raw.map((x) => String(x).trim()).filter(Boolean).slice(0, 12);
  }
  if (typeof raw === 'string') {
    return raw
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean)
      .slice(0, 12);
  }
  return [];
}

/** Public-safe config for the mobile app (no system prompt). */
export function toPublicConfig(full) {
  return {
    trainerName: 'Aura',
    coachSubtitle: full.coachSubtitle,
    welcomeTagline: full.welcomeTagline,
    welcomeDisclaimer: full.welcomeDisclaimer,
    learnMoreUrl: full.learnMoreUrl,
    quickChips: full.quickChips,
  };
}

export async function patchAiCoachSettings(patch) {
  const allowed = [
    'systemPrompt',
    'coachSubtitle',
    'welcomeTagline',
    'welcomeDisclaimer',
    'learnMoreUrl',
    'quickChips',
    'aiProvider',
    'cloudflareModel',
    'openRouterModel',
  ];
  const out = {};
  for (const k of allowed) {
    if (patch[k] !== undefined) out[k] = patch[k];
  }
  if (out.quickChips !== undefined) {
    out.quickChips = normalizeChips(out.quickChips);
  }
  if (out.aiProvider !== undefined) {
    out.aiProvider = normalizeAiProvider(out.aiProvider);
  }
  out.updatedAt = fv().serverTimestamp();
  await coachRef().set(out, { merge: true });
  return readAiCoachSettingsFromFirestore();
}

const MAX_MESSAGES = 40;
const MAX_MESSAGE_CHARS = 6000;

/** @param {{ role: string, content: string }[]} clientMessages */
export function sanitizeClientMessages(clientMessages) {
  if (!Array.isArray(clientMessages)) return [];
  const out = [];
  for (const m of clientMessages.slice(-MAX_MESSAGES)) {
    if (!m || typeof m !== 'object') continue;
    const role = String(m.role || '').toLowerCase();
    if (role !== 'user' && role !== 'assistant') continue;
    let content = String(m.content ?? '');
    if (content.length > MAX_MESSAGE_CHARS) content = content.slice(0, MAX_MESSAGE_CHARS);
    if (!content.trim()) continue;
    out.push({ role, content: content.trim() });
  }
  return out;
}

function cloudflareRunUrl(model) {
  const accountId = config.cloudflareAccountId;
  const encodedModel = encodeURIComponent(model);
  return `https://api.cloudflare.com/client/v4/accounts/${accountId}/ai/run/${encodedModel}`;
}

/**
 * @param {Array<{role: string, content: string}>} messagesIncludingSystem
 */
export async function cloudflareCompletion(messages, modelSlug, temperature = 0.65) {
  if (!isCloudflareConfigured()) {
    throw new Error('Coach AI is not configured (missing CLOUDFLARE_ACCOUNT_ID or CLOUDFLARE_AI_API_TOKEN on server)');
  }
  const model = modelSlug || config.cloudflareAiModel;
  const ac = new AbortController();
  const t = setTimeout(() => ac.abort(), CHAT_TIMEOUT_MS);
  try {
    const res = await fetch(cloudflareRunUrl(model), {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${config.cloudflareAiApiToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        messages,
        temperature,
      }),
      signal: ac.signal,
    });
    const text = await res.text();
    let parsed;
    try {
      parsed = text ? JSON.parse(text) : {};
    } catch {
      throw new Error('Invalid response from AI provider');
    }
    if (!res.ok || parsed.success === false) {
      const errMsg =
        parsed.errors?.[0]?.message ||
        parsed.error ||
        parsed.message ||
        `AI request failed (${res.status})`;
      throw new Error(String(errMsg).slice(0, 280));
    }
    const reply = parsed.result?.response;
    if (typeof reply !== 'string' || !reply.trim()) {
      throw new Error('Empty reply from AI');
    }
    return reply.trim();
  } finally {
    clearTimeout(t);
  }
}

/**
 * @param {Array<{role: string, content: string}>} messagesIncludingSystem
 */
export async function openRouterCompletion(messages, modelSlug, temperature = 0.65) {
  const key = config.openRouterApiKey;
  if (!key) {
    throw new Error('Coach AI is not configured (missing OPENROUTER_API_KEY on server)');
  }
  const model = modelSlug || config.openRouterModel;
  const ac = new AbortController();
  const t = setTimeout(() => ac.abort(), CHAT_TIMEOUT_MS);
  try {
    const res = await fetch(OPENROUTER_URL, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${key}`,
        'Content-Type': 'application/json',
        'HTTP-Referer': 'https://trakkit.app',
        'X-Title': 'Trakkit Fitness App',
      },
      body: JSON.stringify({
        model,
        messages,
        temperature,
      }),
      signal: ac.signal,
    });
    const text = await res.text();
    let parsed;
    try {
      parsed = text ? JSON.parse(text) : {};
    } catch {
      throw new Error('Invalid response from AI provider');
    }
    if (!res.ok) {
      const errMsg =
        (parsed.error && parsed.error.message) ||
        parsed.message ||
        `AI request failed (${res.status})`;
      throw new Error(String(errMsg).slice(0, 280));
    }
    const reply = parsed.choices?.[0]?.message?.content;
    if (typeof reply !== 'string' || !reply.trim()) {
      throw new Error('Empty reply from AI');
    }
    return reply.trim();
  } finally {
    clearTimeout(t);
  }
}

/**
 * Run coach chat with primary provider from settings and automatic failover.
 * @param {Array<{role: string, content: string}>} messagesIncludingSystem
 * @param {Record<string, unknown>} settings
 * @param {{ temperature?: number }} [options]
 */
export async function coachCompletion(messages, settings, options = {}) {
  const temperature = typeof options.temperature === 'number' ? options.temperature : 0.65;
  const primary = normalizeAiProvider(settings.aiProvider);
  const providers = primary === 'openrouter'
    ? ['openrouter', 'cloudflare']
    : ['cloudflare', 'openrouter'];

  let lastError;
  for (const provider of providers) {
    try {
      if (provider === 'cloudflare') {
        if (!isCloudflareConfigured()) continue;
        return await cloudflareCompletion(
          messages,
          settings.cloudflareModel || config.cloudflareAiModel,
          temperature,
        );
      }
      if (provider === 'openrouter') {
        if (!config.openRouterApiKey) continue;
        return await openRouterCompletion(
          messages,
          settings.openRouterModel || config.openRouterModel,
          temperature,
        );
      }
    } catch (err) {
      lastError = err;
      console.warn(`Coach AI provider ${provider} failed:`, err.message);
    }
  }

  throw lastError ?? new Error('Coach AI is not configured');
}

const VALID_BODY_PARTS = new Set([
  'back',
  'legs',
  'chest',
  'shoulders',
  'arms',
  'core',
  'fullBody',
]);

const BODY_PART_LABELS = Object.freeze({
  back: 'Back',
  legs: 'Legs',
  chest: 'Chest',
  shoulders: 'Shoulders',
  arms: 'Arms',
  core: 'Core',
  fullBody: 'Full Body',
});

const PLAN_EXERCISE_COUNT = 5;
const MAX_CATALOG_FOR_LLM = 60;

function exerciseMatchesBodyPart(exercise, bodyPart) {
  const groups = Array.isArray(exercise.muscleGroups) ? exercise.muscleGroups : [];
  if (bodyPart === 'fullBody') {
    return groups.includes('fullBody') || groups.length === 0;
  }
  return groups.includes(bodyPart);
}

function buildExerciseCandidates(allExercises, bodyPart) {
  const primary = allExercises.filter((ex) => exerciseMatchesBodyPart(ex, bodyPart));
  if (primary.length >= PLAN_EXERCISE_COUNT) return primary;

  const seen = new Set(primary.map((ex) => ex.id));
  const fallback = allExercises.filter((ex) => {
    if (seen.has(ex.id)) return false;
    const groups = Array.isArray(ex.muscleGroups) ? ex.muscleGroups : [];
    return groups.includes('fullBody') || groups.length === 0;
  });

  return [...primary, ...fallback];
}

function parsePlanJson(raw) {
  let text = String(raw || '').trim();
  const fence = text.match(/```(?:json)?\s*([\s\S]*?)```/i);
  if (fence) text = fence[1].trim();
  try {
    return JSON.parse(text);
  } catch {
    const start = text.indexOf('{');
    const end = text.lastIndexOf('}');
    if (start >= 0 && end > start) {
      return JSON.parse(text.slice(start, end + 1));
    }
    throw new Error('AI returned invalid plan JSON');
  }
}

/**
 * Generate a 5-exercise workout plan grounded in the Firestore exercise catalog.
 * @param {string} bodyPart
 * @param {string} [userName]
 */
export async function generateWorkoutPlan(bodyPart, userName) {
  const part = String(bodyPart || '').trim();
  if (!VALID_BODY_PARTS.has(part)) {
    const err = new Error(`Invalid bodyPart. Use one of: ${[...VALID_BODY_PARTS].join(', ')}`);
    err.status = 400;
    throw err;
  }

  const snap = await firestore().collection(config.exercisesCollection).get();
  const allExercises = snap.docs
    .map((d) => docToExercise(d.id, d.data()))
    .filter(Boolean);

  if (allExercises.length < PLAN_EXERCISE_COUNT) {
    throw new Error('Exercise catalog too small to generate a plan');
  }

  const candidates = buildExerciseCandidates(allExercises, part).slice(0, MAX_CATALOG_FOR_LLM);
  const catalog = candidates.map((ex) => ({
    id: ex.id,
    name: ex.name || ex.id,
    muscleGroups: Array.isArray(ex.muscleGroups) ? ex.muscleGroups : [],
  }));

  const label = BODY_PART_LABELS[part] || part;
  const settings = await readAiCoachSettingsFromFirestore();

  const system = [
    'You are Aura, an AI personal trainer for Trakkit.',
    'Return ONLY valid JSON with no markdown fences and no extra text.',
    'Schema: {"title":string,"description":string,"exerciseIds":[string,string,string,string,string],"coachMessage":string}',
    `Pick exactly ${PLAN_EXERCISE_COUNT} UNIQUE exerciseIds from the catalog.`,
    'Use only ids that exist in the catalog.',
    'Order exercises from compound to isolation when possible.',
  ].join(' ');

  const userPayload = {
    bodyPart: part,
    bodyPartLabel: label,
    userName: userName || null,
    catalog,
  };

  const messages = [
    { role: 'system', content: system },
    { role: 'user', content: JSON.stringify(userPayload) },
  ];

  const raw = await coachCompletion(messages, settings, { temperature: 0.4 });
  const parsed = parsePlanJson(raw);

  const validIds = new Set(catalog.map((c) => c.id));
  let exerciseIds = Array.isArray(parsed.exerciseIds)
    ? parsed.exerciseIds.map(String).filter((id) => validIds.has(id))
    : [];
  exerciseIds = [...new Set(exerciseIds)];

  for (const item of catalog) {
    if (exerciseIds.length >= PLAN_EXERCISE_COUNT) break;
    if (!exerciseIds.includes(item.id)) exerciseIds.push(item.id);
  }
  exerciseIds = exerciseIds.slice(0, PLAN_EXERCISE_COUNT);

  if (exerciseIds.length < PLAN_EXERCISE_COUNT) {
    throw new Error('Could not build a 5-exercise plan');
  }

  return {
    title: String(parsed.title || `${label} Workout`).trim().slice(0, 80),
    description: String(
      parsed.description || `A ${label.toLowerCase()} session with ${PLAN_EXERCISE_COUNT} exercises.`,
    )
      .trim()
      .slice(0, 400),
    exerciseIds,
    coachMessage: String(
      parsed.coachMessage || `Here's your ${label.toLowerCase()} plan — ${PLAN_EXERCISE_COUNT} moves ready to go.`,
    )
      .trim()
      .slice(0, 500),
  };
}
